# Generated by Django 2.0.1 on 2018-01-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boredometer_app', '0004_auto_20180127_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='section_number',
            field=models.IntegerField(default=0),
        ),
    ]
